Remove arm/v5/v6 from build.yml
hashicorp/consul-terraform-sync pull request #380
Opened 2021-09-08 00:16 UTC by 99

2021-09-08 11:15 UTC, sarahethompson requested changes
Noticed the arm linux packages weren't being uploaded (added some suggestions).
I think this [line](https://github.com/hashicorp/consul-terraform-sync/blob/474c200e144d88028dc59d3b02f458e36929543a/.github/workflows/build.yml#L185) needs updated to `arch: ${{ matrix.goarch }}`

2021-09-08 11:15 UTC, sarahethompson commented on .github/workflows/build.yml
> +          name: ${{ github.event.repository.name }}_${{ needs.get-product-version.outputs.product-version }}_amd64.deb
```suggestion
          name: ${{ github.event.repository.name }}_${{ needs.get-product-version.outputs.product-version }}_armhf.deb
```

2021-09-08 11:15 UTC, sarahethompson commented on .github/workflows/build.yml
> +          path: out/${{ github.event.repository.name }}_${{ needs.get-product-version.outputs.product-version }}_amd64.deb
```suggestion
          path: out/${{ github.event.repository.name }}_${{ needs.get-product-version.outputs.product-version }}_armhf.deb
```

2021-09-08 11:15 UTC, sarahethompson commented on .github/workflows/build.yml
> +          path: out/${{ github.event.repository.name }}-${{ needs.get-product-version.outputs.product-version }}.x86_64.rpm
```suggestion
          path: out/${{ github.event.repository.name }}-${{ needs.get-product-version.outputs.product-version }}.${{ matrix.goarch }}.rpm
```

2021-09-08 11:15 UTC, sarahethompson commented on .github/workflows/build.yml
> +          name: ${{ github.event.repository.name }}-${{ needs.get-product-version.outputs.product-version }}.x86_64.rpm
```suggestion
          name: ${{ github.event.repository.name }}-${{ needs.get-product-version.outputs.product-version }}.${{ matrix.goarch }}.rpm
```

2021-09-09 09:44 UTC, sarahethompson approved these changes

2021-09-09 20:14 UTC, mkam approved these changes
LGTM, though could the commits be squashed when merged to our master branch?

2021-09-10 13:17 UTC, merged